#! python
import json

sim_param = json.load(open('src/model_specs/simulation_parameters.json'), encoding='utf-8')
repetitions = [str(par) for par in range(sim_param['rep_number'])]
d_list = [str(par) for par in sim_param['d_list']]


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='get_simulation_draws.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
        name='get_simulation_draws'
    )
    
    for setup in sim_param["list_of_setups"]:

        for d in d_list:   
        
            rep = repetitions + ['test'] 
            
            for rep_number in rep:
                
                ctx(
                    features='run_py_script',
                    source='get_simulated_samples.py',
                    deps=[
                        ctx.path_to(ctx,'IN_MODEL_SPECS', '{}.json'.format(setup)),
                        ctx.path_to(ctx,'IN_MODEL_CODE', 'main_effect_functions.py'),
                        ctx.path_to(ctx,'IN_MODEL_CODE', 'treatment_effect_functions.py'),
                        ctx.path_to(ctx,'IN_MODEL_CODE', 'propensity_functions.py')
                    ],
                    target=[
                        ctx.path_to(ctx, 'OUT_DATA_' + setup.upper(), 'sample_{}_d={}_rep_{}.json'.format(setup, d, rep_number))
                    ],
                    append=[setup, d, rep_number],
                    name='sample_{}_d={}_rep_{}'.format(setup, d, rep_number)
                )


