#! python
import json

sim_param = json.load(open('src/model_specs/simulation_parameters.json'), encoding='utf-8')
repetitions = [str(par) for par in range(sim_param['rep_number'])]
n_list = [str(par) for par in sim_param['n_list']]
n_test = str(sim_param["n_test_points"])

def build(ctx):


    for setup_name in sim_param["list_of_setups"]:
        for n in n_list:
                for rep_number in repetitions:

                    ctx(
                        features='run_r_script',
                        source='estimate_forest.R',
        
                        deps=[
                            '../../project_paths.r',
                            ctx.path_to(ctx, 'IN_MODEL_CODE', 'sample_size_functions.R'),
                            ctx.path_to(ctx, 'IN_MODEL_CODE', 'n_tree_functions.R'),
                            ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(setup_name)),
                            ctx.path_to(ctx, 'OUT_DATA_' + setup_name.upper(), 'sample_{}_n={}_rep_test.json'.format(setup_name, n_test)),
                            ctx.path_to(ctx, 'OUT_DATA_' + setup_name.upper(), 'sample_{}_n={}_rep_{}.json'.format(setup_name, n, rep_number))

                        ],
                        target=[ctx.path_to(ctx, 'OUT_ANALYSIS_FOREST', 'analysis_data_{}_n={}_rep_{}.json'.format(setup_name,n,rep_number))],
                        append=[n_test, setup_name, n, rep_number],
                        name='get_analysis_data_{}_{}_{}'.format(setup_name, n, rep_number)
                        )

    
    for model in 'baseline', 'max_moves_2':

        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='schelling.py',
            deps=[
                ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
                ctx.path_to(ctx, 'IN_MODEL_CODE', 'agent.py'),
                ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
            ],
            target=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'schelling_{}.pickle'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'log', 'schelling_{}.log'.format(model))
            ],
            append=model,
            name='schelling_{}'.format(model)
        )
